<?xml version='1.0' encoding='UTF-8' ?>
<FSArch Version="3.5.0" Begin="5f52112b" End="5f52112b">
<m tm="5f52112b" tmu="178686" lv="4" cat="/sub_Transport/mod_Serial/in_testRelease/">Ошибка последовательного порта '/dev/pts/6' open: Нет такого файла или каталога.</m>
<m tm="5f52112b" tmu="178721" lv="4" cat="/sub_Transport/">AGLKS &gt; Транспорты: Ошибка запуска входного транспорта 'testRelease'.</m></FSArch>