<?xml version='1.0' encoding='UTF-8' ?>
<FSArch Version="3.6.5" Begin="628b761f" End="628b765b">
<m tm="628b761f" tmu="998310" lv="4" cat="/sub_Transport/mod_Serial/in_testRelease/">Ошибка последовательного порта '/dev/pts/6' open: Нет такого файла или каталога.</m>
<m tm="628b761f" tmu="998310" lv="4" cat="/sub_Transport/mod_Serial/in_testRelease/">Ошибка последовательного порта '/dev/pts/6' open: Нет такого файла или каталога.</m>
<m tm="628b761f" tmu="998344" lv="4" cat="/sub_Transport/">AGLKS &gt; Транспорты: Ошибка запуска входного транспорта 'testRelease'.</m>
<m tm="628b761f" tmu="998344" lv="4" cat="/sub_Transport/">AGLKS &gt; Транспорты: Ошибка запуска входного транспорта 'testRelease'.</m>
<m tm="628b7629" tmu="32505" lv="4" cat="/sub_DAQ/mod_System/cntr_AutoDA/">AGLKS &gt; Сбор Данных &gt; System &gt; AutoDA: Элемент 'Interface_virbr0-nic' отсутствует!</m>
<m tm="628b7633" tmu="32475" lv="4" cat="/sub_DAQ/mod_System/cntr_AutoDA/">AGLKS &gt; Сбор Данных &gt; System &gt; AutoDA: Элемент 'Interface_virbr0-nic' отсутствует!</m>
<m tm="628b763d" tmu="32354" lv="4" cat="/sub_DAQ/mod_System/cntr_AutoDA/">AGLKS &gt; Сбор Данных &gt; System &gt; AutoDA: Элемент 'Interface_virbr0-nic' отсутствует!</m>
<m tm="628b7647" tmu="89685" lv="4" cat="/sub_DAQ/mod_System/cntr_AutoDA/">AGLKS &gt; Сбор Данных &gt; System &gt; AutoDA: Элемент 'Interface_virbr0-nic' отсутствует!</m>
<m tm="628b7651" tmu="32333" lv="4" cat="/sub_DAQ/mod_System/cntr_AutoDA/">AGLKS &gt; Сбор Данных &gt; System &gt; AutoDA: Элемент 'Interface_virbr0-nic' отсутствует!</m>
<m tm="628b765b" tmu="32277" lv="4" cat="/sub_DAQ/mod_System/cntr_AutoDA/">AGLKS &gt; Сбор Данных &gt; System &gt; AutoDA: Элемент 'Interface_virbr0-nic' отсутствует!</m></FSArch>